name: DataWelder tests

on: [push]

jobs:
  linters:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: install linters
        run: |
          pip install flake8 mypy
      - name: run linters
        run: |
          flake8 datawelder
      - name: run mypy
        run: |
          mypy datawelder

  unit_tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: [linters]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.8.x"
    - name: install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install -e .[test]
    - name: run DataWelder unit tests
      run: |
        . venv/bin/activate
        pytest datawelder -x --showlocals --cov=datawelder --cov-report=xml

  doctest:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: [linters,unit_tests]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.8.x"
    - name: install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install -e .[test]
    - name: run readme doctest
      run: |
        . venv/bin/activate
        python readme_doctest.py
